### ISSUE TITLE
Infinite loop in test causing tests to never end

### ISSUE THREAD

**Issue by lionralfs** [vaneenige/unvault#3]
This test:
https://github.com/vaneenige/unvault/blob/4b7bd22faedc5020bb268898e9dde49fdf9fbe6b/test/index.js#L22
causes an infinite `setTimeout` loop which results in the tests never ending and TravisCI to report tests as failing.

**Comment by vaneenige** [comment]
I've updated the test to only add trackers that update once. Also added an extra check to make sure a tracker still exists when its update is finished (otherwise it added it again).

Updated test: f4231eddf2b799654431e7c3d26cb159a1899f44
Updated lib: 8f110cf0ecf164938595bc6056043e0b5b19f9ea

Travis build passed! 🎉
